# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/kedro-inspect',
                'doc_host': 'https://noklam.github.io',
                'git_url': 'https://github.com/noklam/kedro-inspect',
                'lib_path': 'kedro_inspect'},
  'syms': {'kedro_inspect.core': {'kedro_inspect.core.foo': ('core.html#foo', 'kedro_inspect/core.py')}}}
